# Generated by Django 4.0.1 on 2022-01-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Shininess', models.FloatField()),
                ('bumpmap', models.ImageField(upload_to='bumpmaps')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('texture', models.ImageField(upload_to='textures')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='main.material')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.FileField(upload_to='models')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.item')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.part'),
        ),
    ]
