# Generated by Django 4.0.1 on 2022-03-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='items')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repeat', models.IntegerField()),
                ('bumpmap', models.ImageField(blank=True, null=True, upload_to='bumpmaps')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('texture', models.ImageField(blank=True, null=True, upload_to='textures')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='main.material')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.FileField(null=True, upload_to='models')),
                ('bumpmap', models.ImageField(blank=True, null=True, upload_to='textures')),
                ('default', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.pattern')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ManyToManyField(to='main.Material')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.part')),
            ],
        ),
    ]
