# Generated by Django 4.0.1 on 2022-01-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='bumpmap',
        ),
        migrations.AddField(
            model_name='item',
            name='bumpmap',
            field=models.ImageField(default=0, upload_to='bumpmaps'),
            preserve_default=False,
        ),
    ]
