# Generated by Django 4.0.1 on 2022-03-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_patina_item_patinad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='shininess',
            field=models.FloatField(default=300),
        ),
    ]
