# Generated by Django 4.0.1 on 2022-01-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_material_bumpmap_item_bumpmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='Item',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='texture',
            field=models.ImageField(blank=True, upload_to='textures'),
        ),
    ]
