# Generated by Django 4.0.1 on 2022-03-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pattern_shininess'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='textures'),
        ),
    ]
