# Generated by Django 4.0.1 on 2022-03-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pattern_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmaterials',
            old_name='material',
            new_name='materials',
        ),
    ]
