# Generated by Django 4.0.1 on 2022-03-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_material_itemmaterials_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmaterials',
            old_name='materials',
            new_name='material',
        ),
    ]
