# Generated by Django 4.0.1 on 2022-01-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_item_bumpmap_material_bumpmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='bumpmap',
            field=models.ImageField(null=True, upload_to='bumpmaps'),
        ),
    ]
