# Generated by Django 4.0.1 on 2022-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_material_part_alter_material_bumpmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='bumpmap',
        ),
        migrations.AddField(
            model_name='part',
            name='bumpmap',
            field=models.ImageField(blank=True, null=True, upload_to='bumpmaps'),
        ),
    ]
