# Generated by Django 4.0.1 on 2022-01-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_itemmaterials_material_itemmaterials_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaterials',
            name='material',
        ),
    ]
