# Generated by Django 4.0.1 on 2022-01-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_itemmaterials_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaterials',
            name='material',
            field=models.ManyToManyField(to='main.Material'),
        ),
    ]
